
package com.dv.persistencia.cliente.auto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuarioServicioService", targetNamespace = "http://usuarios.servicios.persistencia.dv.com/", wsdlLocation = "http://localhost:8888/UsuarioServicioService.wsdl")
public class UsuarioServicioService
    extends Service
{

    private final static URL USUARIOSERVICIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSERVICIOSERVICE_EXCEPTION;
    private final static QName USUARIOSERVICIOSERVICE_QNAME = new QName("http://usuarios.servicios.persistencia.dv.com/", "UsuarioServicioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/UsuarioServicioService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSERVICIOSERVICE_WSDL_LOCATION = url;
        USUARIOSERVICIOSERVICE_EXCEPTION = e;
    }

    public UsuarioServicioService() {
        super(__getWsdlLocation(), USUARIOSERVICIOSERVICE_QNAME);
    }

    public UsuarioServicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSERVICIOSERVICE_QNAME, features);
    }

    public UsuarioServicioService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSERVICIOSERVICE_QNAME);
    }

    public UsuarioServicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSERVICIOSERVICE_QNAME, features);
    }

    public UsuarioServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioServicio
     */
    @WebEndpoint(name = "UsuarioServicioPort")
    public UsuarioServicio getUsuarioServicioPort() {
        return super.getPort(new QName("http://usuarios.servicios.persistencia.dv.com/", "UsuarioServicioPort"), UsuarioServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioServicio
     */
    @WebEndpoint(name = "UsuarioServicioPort")
    public UsuarioServicio getUsuarioServicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://usuarios.servicios.persistencia.dv.com/", "UsuarioServicioPort"), UsuarioServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSERVICIOSERVICE_EXCEPTION!= null) {
            throw USUARIOSERVICIOSERVICE_EXCEPTION;
        }
        return USUARIOSERVICIOSERVICE_WSDL_LOCATION;
    }

}
